### ISSUE TITLE
Set what times to update?

### ISSUE THREAD

**Issue by Pliind** [boghammar/MMM-SL-PublicTransport#18]
Don't know if this is an issue or my fault.
The time is now 16:22 and last bus-time that updates was 13:04. 

I know we want to keep the api-calls to a minimum, so my question is, is it possible to add a time frame for when to update the timetable? or force-sync? I have mine at work so only need it to start showing busses around 17.00 and forth. And if i deply a mirror at home i only need it to show times frequently from 6am to 9am.

**Comment by boghammar** [comment]
Right, let's see here. It seems as this is two issues, one possible problem and one feature request.

**The Issue**
The update frequency is set in the configuration so if the time is 16:22 and the last update was at 13:04 there's a problem or you have a very long setting for your _updateInterval_. There is a known problem with the SL (TrafikLab) services. Please see the note in the updated [readme.md](https://github.com/boghammar/MMM-SL-PublicTransport/blob/master/README.md).  This problem should however render an error message in red, do you see that? If not please provide some more information. Is it possible for you to get the client side logs (the javascript logs in the browser) and the server side logs from the MM service?

**The feature request**
That's a good point to be able to set a schedule when it's important to do updates. I'll add this as a feature request and add it to the module when I get the time. I'm not quite sure on how to implement that yet but it should not be impossible.

**Comment by Pliind** [comment]
Issue: 
I'm using the sample-codes updateintervall (maybe it's not appropriet?) 
Also getting an issue: "11:30 service 600 Error: gettaddrinfo EAI-AGAIN.api.sl.se 80

Feature:
Sounds awesome! :)

**Comment by boghammar** [comment]
**About the update issue**
The sample updateintervall should be ok, it's every 5 minutes which should be within the allowed limit for an ordinary account at TrafikLab.

Is it possible for you to **send logfiles** both from the client side and the server side. In order to understand what happens I need to see them. 

If you have no clue what I'm talking about I'll post a description on how to get the logfiles but it might take some time to do the description.

**About the EAI-AGAIN error**
I have never seen this. Googling on the error reveals that there's a problem doing a DNS lookup from your location. 
- Do you normally have network issues not being able to connect to sites?
- Does it recover from this so that after a while you get the correct departure times?

**New Feature**
I'll code that feature when I get the time. Right now it's a bit hectic with Christmas coming up and all but maybe during the holidays :). Follow the [enhancement feature](https://github.com/boghammar/MMM-SL-PublicTransport/issues/19).

**Comment by boghammar** [comment]
Hi Again

please checkout the latest release that has a feature to set when to increase the update frequency.
