### ISSUE TITLE
Using multiple stations

### ISSUE THREAD

**Issue by Craxens** [boghammar/MMM-SL-PublicTransport#20]
First of all, thanks for this module, it's working like a charm for me.

I don't have any issue to report more of a request.

I would like to be able to use multiple stations for depatures.
ie. My daughter always takes the train (18) from 9181 but my other daughter need to take bus 'yyy' from station 9184.
if I use multiple instances of the module it only duplicates the data from the first instance to the next....

it would be great if i can choose stations the same way i choose which lines i want to fetch the data from.

**Comment by boghammar** [comment]
I did not see that one coming :)

Great that you like it, always nice with feedback and nice to hear that it works since I have had some problems with the TrafikLab API not responding correctly. 

Great idea, however this will cost you 2 API calls to Trafiklab everytime. The free account that you have only allows for 10000 calls/month which with 1 call is one call every 4.32 minutes so with 2 calls every update you must set updateInterval: 4.32*2*60*100 instead of updateInterval: 4.32*60*100 to not hit the monthly limit.

That said, I have [another request](https://github.com/boghammar/MMM-SL-PublicTransport/issues/19) that will enable updates during specific times only, so when I have that update in place this would be quite usable.

As I said in the [other feature request](https://github.com/boghammar/MMM-SL-PublicTransport/issues/18): I'll code this feature when I get the time. Right now it's a bit hectic with Christmas coming up and all but maybe during the holidays :). You can follow/subscribe to this request to get notified when I update.

**Comment by boghammar** [comment]
This functionality is now available in the latest release. Please test and provide feedback.
