### ISSUE TITLE
Filter on Transport Type per station

### ISSUE THREAD

**Issue by antonstarlid** [boghammar/MMM-SL-PublicTransport#26]
Sort out transport type, if the stop has more then one type but you only like to see the trains from there as an example.

**Comment by htilly** [comment]
+1 on this.
Maybe put a symbol in front of the line number?

I.e. If its a bus = https://fontawesome.com/icons/bus?style=solid
if a train = https://fontawesome.com/icons/train?style=solid
if a subway = https://fontawesome.com/icons/subway?style=solid.

.. and thanks for a great module!

**Comment by boghammar** [comment]
Thanks for that, it's on its way as soon as I get around to it ;). 
Not that much work actually and I have a branch with a "first attempt" on this Milestone1.4.

**Comment by boghammar** [comment]
Released in 1.5

**Comment by antonstarlid** [comment]
I think you got this the whole wrong way and i very disappointed, not show what the actually ride is that you use.

It is the actually ride you like to show in list, as an example if you have "Train/Buss/Subway" on one stop and you just like to see the "Train" in the list that is the "Transport Type" and has nothing to do whit icons as "htilly" seems to think or your for that matter as it seems like i still unchanged if you look at the documentation for latest release.

**Comment by boghammar** [comment]
I have somewhat of a hard time to follow you there but anyway, yes that was a mistake from my side. I confused the "ride icon" requirement with this one.

I will reopen this one, rephrase the title and plan for this in a future release.

BTW: You know that you can always clone the repository, develop the functionality that you require and if you so choose, submit a pull request.

**Comment by htilly** [comment]
Well, I'm very happy with this module and thankful that it keeps getting developed, for free!

Awesome that we now have the option of a nice icon in front of the line. Thanks for this!

But I agree with @antonstarlid that this specific topic should filter on transport type. Sorry if I added an additional request in this thread. 
I also still have the need of filtering of type, so it´s great that this thread is still open. 
However, I have solved the problem by defining the specific lines that leave the station, and this just got much better since the 1.5 release!

BR
Tilly

**Comment by boghammar** [comment]
Thanks for that @htilly 

Well it seems that this feature was not so hard to fix and since it's the most requested feature so far with 2 users requesting it, it's now in place, hopefully ;)

It's done so that you tell which transport types you don't want to see with the parameter ``excludeTransportTypes``, hope that works for you guys.

Please test and see if it works and report back any issues.
