### ISSUE TITLE
Dont show departures that have left the station

### ISSUE THREAD

**Issue by TimerWolf** [boghammar/MMM-SL-PublicTransport#27]
Possibility to automatic remove and not show the one that left in the list, is no need to have them there if them left the current station

**Comment by boghammar** [comment]
In the latest commit 2e3aace a new config parameter ``omitDeparturesLeft`` that if set to true will not show departures that has left the station. The feature only works with ``useDisplayTime`` set to false (well if used it will never show left departures anyway since there currently are no updates of displayTime between ``uiUpdateInterval`` currently, see issue #25).

Please test and report any issues found with this feature.

**Comment by boghammar** [comment]
No feedback but it works for me ;) so closing this one.
